name: Build and Test hel-compress

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize Pacman and Install Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git gcc make pkgconf gtk3 zlib bzip2 zstd openssl

      - name: Build Project Inside Folder
        run: |
          cd hel-compress
          make

      - name: Build Arch Linux Package from Root
        run: |
          useradd -m builder
          chown -R builder:builder .
          chmod 777 .
          
          # تشغيل makepkg من جذر المشروع حيث يوجد PKGBUILD بالخارج تماماً
          su - builder -c "cd $GITHUB_WORKSPACE && makepkg -si --noconfirm"
